"""Major US freight market hubs used as quick-select options."""

MAJOR_FREIGHT_HUBS = [
    "San Bernardino, CA",
    "Ontario, CA",
    "Los Angeles, CA",
    "Fresno, CA",
    "Oakland, CA",
    "Phoenix, AZ",
    "Las Vegas, NV",
    "Salt Lake City, UT",
    "Seattle, WA",
    "Portland, OR",
    "Dallas, TX",
    "Houston, TX",
    "San Antonio, TX",
    "El Paso, TX",
    "Laredo, TX",
    "Chicago, IL",
    "Indianapolis, IN",
    "Columbus, OH",
    "Memphis, TN",
    "Nashville, TN",
    "Atlanta, GA",
    "Charlotte, NC",
    "Jacksonville, FL",
    "Miami, FL",
    "Kansas City, MO",
    "St. Louis, MO",
    "Minneapolis, MN",
    "Denver, CO",
    "Newark, NJ",
    "Harrisburg, PA",
]